#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#Para cargar el fondo de pantalla cada vez que se inicie
feh --bg-fill /home/erickbuster/Desktop/Images/fondo.jpg
#Launchear la polybar
~/.config/polybar/./launch.sh
#Seguimiento del raton en las terminales
bspc config focus_follows_pointer true
#Aplicar los bordeados en la terminal
picom --experimental-backends &
bspc config border_width 0

xsetroot -cursor_name left_ptr &
